# Generated by Django 5.1.6 on 2025-02-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='path',
            field=models.TextField(default=''),
        ),
    ]
