# Generated by Django 5.1.6 on 2025-02-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapi', '0002_userfile_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='path',
            field=models.TextField(),
        ),
    ]
